import streamlit as st
import anthropic
import os

# Streamlit app
st.title("DreamCatcher: Dream Interpretation App")

# Input box for the dream
dream_input = st.text_area("Enter your dream here:", height=150)

# Button to trigger the interpretation
if st.button("Interpret Dream"):
    if dream_input:
        # Initialize the Anthropic client
        client = anthropic.Anthropic(
            api_key=os.environ.get("ANTHROPIC_API_KEY")
        )

        # Create the message for interpretation
        message = client.messages.create(
            model="claude-3-opus-20240229",
            max_tokens=2000,
            temperature=1,
            system="You are an AI assistant with a deep understanding of dream interpretation and symbolism. Your task is to provide users with insightful and meaningful analyses of the symbols, emotions, and narratives present in their dreams. Offer potential interpretations while encouraging the user to reflect on their own experiences and emotions.",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": dream_input
                        }
                    ]
                }
            ]
        )

        # Display the interpretation
        st.subheader("Dream Interpretation:")
        # Extract and display only the text content
        interpretation_text = message.content[0].text if message.content else "No interpretation available."
        st.write(interpretation_text)
    else:
        st.warning("Please enter a dream to interpret.")

# Add some information about the app
st.sidebar.header("About DreamCatcher")
st.sidebar.info(
    "DreamCatcher is an AI-powered dream interpretation app. "
    "Enter your dream in the text box, and our AI will provide "
    "insights and potential meanings based on dream symbolism "
    "and interpretation techniques."
)

# Disclaimer
st.sidebar.header("Disclaimer")
st.sidebar.warning(
    "The interpretations provided by this app are generated by an AI model "
    "and should be considered as possibilities rather than definitive meanings. "
    "Dreams are highly personal, and their true significance can often only be "
    "determined by the dreamer upon reflection."
)
